services:
  web-rutanet: # En minúsculas
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-rutanet # En minúsculas
    ports:
      - "8388:80"
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge